// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://jkmrtmsygflaagrfsgnw.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImprbXJ0bXN5Z2ZsYWFncmZzZ253Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDkyNDMyODcsImV4cCI6MjAyNDgxOTI4N30.Hf8asYd9-4caed88gH9J9PVIzpjqOgI2ykJe67s5kCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);